title: Proposed DDI-C enhancements
description: DDI metadata schema as proposed by the NCRN Cornell project.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
